repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: make clang-format
        language: system
        pass_filenames: false
      - id: clang-tidy
        name: clang-tidy
        entry: make clang-tidy
        language: system
        pass_filenames: false

