name: build-test-release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-i686
            cc: gcc-i686-linux-gnu
            runner: ubuntu-latest
            pkg_manager: sudo apt-get update && sudo apt-get install -y
            packages: gcc-i686-linux-gnu
            dist: targz-pkg

          - name: linux-x86-64
            cc: gcc-x86-64-linux-gnu
            runner: ubuntu-latest
            pkg_manager: sudo apt-get update && sudo apt-get install -y
            packages: gcc-x86-64-linux-gnu
            dist: targz-pkg

          - name: linux-aarch64
            cc: gcc-aarch64-linux-gnu
            runner: ubuntu-latest
            pkg_manager: sudo apt-get update && sudo apt-get install -y
            packages: gcc-aarch64-linux-gnu
            dist: targz-pkg

          - name: linux-arm-gnueabihf
            cc: gcc-arm-linux-gnueabihf
            runner: ubuntu-latest
            pkg_manager: sudo apt-get update && sudo apt-get install -y
            packages: gcc-arm-linux-gnueabihf
            dist: targz-pkg

          - name: linux-arm-gnueabi
            cc: gcc-arm-linux-gnueabi
            runner: ubuntu-latest
            pkg_manager: sudo apt-get update && sudo apt-get install -y
            packages: gcc-arm-linux-gnueabi
            dist: targz-pkg

          - name: macos-arm64
            cc: clang
            runner: macos-latest
            pkg_manager: brew install
            packages: coreutils
            dist: targz-pkg

          - name: macos-x86-64
            cc: clang
            runner: macos-15-intel
            pkg_manager: brew install
            packages: coreutils
            dist: targz-pkg

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          ${{ matrix.pkg_manager }} ${{ matrix.packages }}

      - name: clang-fomat
        run: |
          make CC=${{ matrix.cc }} clang-format

      - name: clang-tidy
        run: |
          make CC=${{ matrix.cc }} clang-tidy

      - name: build
        run: |
          make CC=${{ matrix.cc }}

      - name: dist
        run: |
          make CC=${{ matrix.cc }} ${{ matrix.dist }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    needs:
      - build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: install commitizen
        run: pip install commitizen

      - name: get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" | tee -a $GITHUB_OUTPUT

      - name: generate changelog
        run: |
          cz changelog ${{ steps.get_version.outputs.VERSION }} --file-name changelog_body.md
          cat changelog_body.md

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog_body.md
          name: Version ${{ steps.get_version.outputs.version }}
          draft: true
          files: |
            artifacts/**/*
