name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux Distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-x86-64-linux-gnu \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            gcc-arm-linux-gnueabihf \
            gcc-i686-linux-gnu

      - name: Build
        run: |
          set -eux
          make CC=x86_64-linux-gnu-gcc targz-pkg tarxz-pkg
          make CC=aarch64-linux-gnu-gcc targz-pkg tarxz-pkg
          make CC=arm-linux-gnueabi-gcc targz-pkg tarxz-pkg
          make CC=arm-linux-gnueabihf-gcc targz-pkg tarxz-pkg
          make CC=i686-linux-gnu-gcc targz-pkg tarxz-pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist-artifacts
          path: dist/*

  build-windoes-mscvrt:
    name: Build Windows Distributions with MSCVRT
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64

      - name: Build
        run: |
          set -eux
          make CC=i686-w64-mingw32-gcc zip-pkg PKG_SUFFIX="-msvcrt"
          make CC=x86_64-w64-mingw32-gcc zip-pkg PKG_SUFFIX="-msvcrt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist-artifacts-msvcrt
          path: dist/*

  build-windoes-ucrt:
    name: Build Windows Distributions with UCRT
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          sudo apt-get update \
          eval $(make -f Makefile.llvm-mingw)

      - name: Build
        run: |
          set -eux
          make CC=i686-w64-mingw32-clang zip-pkg PKG_SUFFIX="-msvcrt"
          make CC=x86_64-w64-mingw32-clang zip-pkg PKG_SUFFIX="-ucrt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist-artifacts-ucrt
          path: dist/*

  build-macos-arm64:
    name: Build macOS Distributions arm64
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          set -eux
          make CC=clang targz-pkg tarxz-pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist-artifacts-arm64
          path: dist/*

  build-macos-x86_64:
    name: Build macOS Distributions x86_64
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          set -eux
          make CC=clang targz-pkg tarxz-pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist-artifacts-x86_64
          path: dist/*

  release:
    if: github.event_name != 'workflow_dispatch'
    name: Create GitHub Release
    needs:
      - build-linux
      - build-windoes-mscvrt
      - build-windoes-ucrt
      - build-macos-arm64
      - build-macos-x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Install commitizen
        run: pip install commitizen

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" | tee -a $GITHUB_OUTPUT

      - name: Generate changelog
        run: |
          cz changelog ${{ steps.get_version.outputs.VERSION }} --file-name changelog_body.md
          cat changelog_body.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog_body.md
          name: Version ${{ steps.get_version.outputs.version }}
          draft: true
          files: |
            artifacts/**/*
