name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-linux:
    name: build linux (i686, x86_64, arm64, armhf, armel)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-i686-linux-gnu \
            gcc-x86-64-linux-gnu \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf \
            gcc-arm-linux-gnueabi

      - name: build
        run: |
          set -eux
          make CC=i686-linux-gnu-gcc targz-pkg
          make CC=x86_64-linux-gnu-gcc targz-pkg
          make CC=aarch64-linux-gnu-gcc targz-pkg
          make CC=arm-linux-gnueabihf-gcc targz-pkg
          make CC=arm-linux-gnueabi-gcc targz-pkg

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist-artifacts
          path: dist/*

  build-windoes-mscvrt:
    name: build windows msvrct (i686, x86_64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64

      - name: build
        run: |
          set -eux
          make CC=i686-w64-mingw32-gcc zip-pkg PKG_SUFFIX="-msvcrt"
          make CC=x86_64-w64-mingw32-gcc zip-pkg PKG_SUFFIX="-msvcrt"

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist-artifacts-msvcrt
          path: dist/*

  build-windoes-ucrt:
    name: build windows ucrt (i686, x86_64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          sudo apt-get update
          make -f Makefile.llvm-mingw

      - name: build
        run: |
          set -eux
          eval $(make -f Makefile.llvm-mingw)
          make CC=i686-w64-mingw32-clang zip-pkg PKG_SUFFIX="-ucrt"
          make CC=x86_64-w64-mingw32-clang zip-pkg PKG_SUFFIX="-ucrt"

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist-artifacts-ucrt
          path: dist/*

  build-macos-arm64:
    name: build macOS (arm64)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          set -eux
          make CC=clang targz-pkg

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist-artifacts-arm64
          path: dist/*

  build-macos-x86_64:
    name: build macOS (x86_64)
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          set -eux
          make CC=clang targz-pkg

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist-artifacts-x86_64
          path: dist/*

  release:
    if: github.event_name != 'workflow_dispatch'
    name: create github release
    needs:
      - build-linux
      - build-windoes-mscvrt
      - build-windoes-ucrt
      - build-macos-arm64
      - build-macos-x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: install commitizen
        run: pip install commitizen

      - name: get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" | tee -a $GITHUB_OUTPUT

      - name: generate changelog
        run: |
          cz changelog ${{ steps.get_version.outputs.VERSION }} --file-name changelog_body.md
          cat changelog_body.md

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog_body.md
          name: Version ${{ steps.get_version.outputs.version }}
          draft: true
          files: |
            artifacts/**/*
